Address some issues reported by static analyzers (Coverity Scan, clang)
Error: REVERSE_INULL:
src/libical-glib/i-cal-object.c:355: deref_ptr: Directly dereferencing pointer "iobject".
src/libical-glib/i-cal-object.c:365: check_after_deref: Null-checking "iobject" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
  363|
  364|       if (is_global_memory) {
  365|->         if (iobject) {
  366|               GlobalData *gd;
  367|

------------------------------------------------------------------

Error: ALLOC_FREE_MISMATCH:
src/libical/vcomponent_cxx.cpp:922: alloc: Allocation of memory which must be freed using "operator delete".
src/libical/vcomponent_cxx.cpp:922: assign: Assigning: "related_param" = "trigger_prop->get_first_parameter(icalparameter_kind const(ICAL_RELATED_PARAMETER))".
src/libical/vcomponent_cxx.cpp:979: free: Calling "free" frees "related_param" using "free" but it should have been freed using "operator delete".
  977|
  978|           if (related_param != NULL) {
  979|->             free(related_param);
  980|           }
  981|

------------------------------------------------------------------

Error: IDENTIFIER_TYPO:
libical-3.0.5/src/python/Component.py:796: identifier_typo: Using "properites" appears to be a typo:
* Identifier "properites" is only known to be referenced here, or in copies of this code.
* Identifier "properties" is referenced elsewhere at least 18 times.

src/python/Component.py:796: remediation: Should identifier "properites" be replaced by "properties"?
src/python/Component.py:138: identifier_use: Example 2: Using identifier "properties".
src/python/Component.py:674: identifier_use: Example 3: Using identifier "properties".
src/python/test.py:274: identifier_use: Example 4: Using identifier "properties" (9 total uses in this function).
src/python/test.py:393: identifier_use: Example 5: Using identifier "properties".
  794|       def duration(self, value=None):
  795|           if value != None:
  796|->             due = self.properites('DUE')
  797|               for d in due:
  798|                   self.remove_property(d)  # Clear DUE properties

Signed-off-by: Allen Winter <allen.winter@kdab.com>