icaldirset - rename icaldirset_modify argument 'new'
Don't use 'new' as an argument name since that's a C++ keyword.

Fixes:
```
error: invalid parameter name: 'new' is a keyword
```